services:
  - type: web
    name: lecsumm-api
    env: docker
    plan: free
    rootDir: backend-springboot
    envVars:
      - key: MONGODB_URI
      - key: JWT_SECRET
      - key: GOOGLE_CLIENT_ID
        value: 646426743846-qu5hrl9boiu660qp5kq3hsaj9cne07no.apps.googleusercontent.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://lecsumm.indevs.in,http://localhost:5173
      - key: AI_SERVICE_URL
